# Generated by Django 4.2.6 on 2023-11-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vender_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('vender_code', models.CharField(max_length=20)),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
            ],
        ),
    ]
